### ISSUE TITLE
Contributer

### ISSUE THREAD

**Issue by hamzalodhi2023** [Eftakharshaikh/PortfolioWebsite#1]
![Screenshot 2024-01-19 120023](https://github.com/Eftakharshaikh/PortfolioWebsite/assets/134397582/f6173cf3-ee19-4a48-8de5-ae520a35f930)
Add website link.

**Comment by Eftakharshaikh** [comment]
so how you going to change my portfolio

**Comment by hamzalodhi2023** [comment]
Add website link.

**Comment by hamzalodhi2023** [comment]
![Screenshot 2024-01-19 120023](https://github.com/Eftakharshaikh/PortfolioWebsite/assets/134397582/fa5825e9-d073-44f2-a411-fb7bcacb6e05)

**Comment by Eftakharshaikh** [comment]
https://eftakharshaikh.github.io/PortfolioWebsite/

**Comment by Eftakharshaikh** [comment]
screen short ???

**Comment by hamzalodhi2023** [comment]
Go repository setting.
![Screenshot 2024-01-19 121736](https://github.com/Eftakharshaikh/PortfolioWebsite/assets/134397582/b53f5739-01b9-4588-a0bd-6bc5b484b4c1)

**Comment by Eftakharshaikh** [comment]
done

**Comment by hamzalodhi2023** [comment]
Click pages tab.
![Uploading Screenshot 2024-01-19 121903.png…]()

**Comment by hamzalodhi2023** [comment]
select main and root option and click on save button.
![Uploading Screenshot 2024-01-19 122001.png…]()

**Comment by Eftakharshaikh** [comment]
![Screenshot (49)](https://github.com/Eftakharshaikh/PortfolioWebsite/assets/147795895/8dfede37-14cd-4934-ad67-7112875903ad)

**Comment by hamzalodhi2023** [comment]
Ok Nice !👍

**Comment by Eftakharshaikh** [comment]
any thing?

**Comment by hamzalodhi2023** [comment]
add readme.


# MY PORTFOLIO WEBSITE🎉
### Author - Eftakhar Shaikh
Click Here to visit : https://eftakharshaikh.github.io/PortfolioWebsite/<br><br>
## Clone Repository ✌
### Step 1: Install Git (if not already installed)
Make sure you have Git installed on your machine. If not, download and install it from <a href="https://git-scm.com/" >Git's official website</a>.
### Step 2: Open Terminal or Command Prompt
Open your terminal or command prompt on your local machine.
### Step 3: Navigate to Your Desired Directory
Use the cd command to navigate to the directory where you want to clone the "PortfolioWebsite" repository.
```bash
cd path/to/your/directory
```
### Step 4: Clone the Repository
Run the following command to clone the "PortfolioWebsite" repository:
```bash
git clone https://eftakharshaikh.github.io/PortfolioWebsite.git
```
### Step 5: Navigate to the Cloned Directory
Move into the cloned "PortfolioWebsite" directory using the cd command:
```bash
cd PortfolioWebsite
```

## You have successfully cloned the repository! Feel free to explore the contents !! 👍

**Comment by Eftakharshaikh** [comment]
so you add Read me?

**Comment by hamzalodhi2023** [comment]
I added README.md

**Comment by Eftakharshaikh** [comment]
ok

**Comment by hamzalodhi2023** [comment]
I am recoding this website.

**Comment by Eftakharshaikh** [comment]
i a going for namaz  e jumma

**Comment by hamzalodhi2023** [comment]
OK. I am also going to offer Namaz e Jummah.

**Comment by hamzalodhi2023** [comment]
I need you HD photo.

**Comment by hamzalodhi2023** [comment]
I need your HD photo

**Comment by Eftakharshaikh** [comment]
as salamu allay kum! what it mean? good first issue and question

**Comment by hamzalodhi2023** [comment]
To upgrade the repository rating.

**Comment by Eftakharshaikh** [comment]
ok

**Comment by hamzalodhi2023** [comment]
Asalam'alaykum! Please give me your HD photo for portfolio header sample is attached herewith.
![joshua-mayo-KboMbhlRgGY-unsplash](https://github.com/Eftakharshaikh/PortfolioWebsite/assets/134397582/147caeb9-f812-45c5-83b8-649a11166bd5)

**Comment by Eftakharshaikh** [comment]
![IMG_2491](https://github.com/Eftakharshaikh/PortfolioWebsite/assets/147795895/1200a961-e866-4409-b1fc-3a1e1772ccf2)
is it ok?

**Comment by hamzalodhi2023** [comment]
I need landscape image.

**Comment by hamzalodhi2023** [comment]
Nice photo thanks.

**Comment by Eftakharshaikh** [comment]
![20190204_111301](https://github.com/Eftakharshaikh/PortfolioWebsite/assets/147795895/ca8219a7-892a-47d9-bf27-7682b9f64d8b)

**Comment by hamzalodhi2023** [comment]
Thanks.

**Comment by hamzalodhi2023** [comment]
Asalam'alaykum! Your portfolio has been completed.

**Comment by Eftakharshaikh** [comment]
walekum as salam, resume ka ek page aad karna hai, jis ko mai pdf me download kar sakta hu

**Comment by hamzalodhi2023** [comment]
share me.

**Comment by Eftakharshaikh** [comment]
[Eftakhar Shaikh Data Analyst (1) (2).pdf](https://github.com/Eftakharshaikh/PortfolioWebsite/files/14001349/Eftakhar.Shaikh.Data.Analyst.1.2.pdf)

**Comment by Eftakharshaikh** [comment]
![Screenshot (54)](https://github.com/Eftakharshaikh/PortfolioWebsite/assets/147795895/b2268832-c81b-4716-a965-f9ec4f92496e)
Over Laping ho rah hai, contcat information nahi hai,

**Comment by hamzalodhi2023** [comment]
on which device do you open the website

**Comment by Eftakharshaikh** [comment]
laptop

**Comment by hamzalodhi2023** [comment]
further Media Query for responsivness  I will added soon, inshallah

**Comment by hamzalodhi2023** [comment]
> laptop

Ok i resolve the issue, no problem

**Comment by Eftakharshaikh** [comment]
Hey amigos! I'm Eftakhar Shaikh, a data magician turning numbers into compelling tales. can we adjust this line with my name in creative way? @main top

**Comment by Eftakharshaikh** [comment]
masha allaha website is looking very good as compare mine 
hahah

**Comment by hamzalodhi2023** [comment]
> Hey amigos! I'm Eftakhar Shaikh, a data magician turning numbers into compelling tales. can we adjust this line with my name in creative way? @main top

Where do you want to add

**Comment by Eftakharshaikh** [comment]
Hey amigos! I'm Eftakhar Shaikh, a data magician turning numbers into compelling tales.

this line

**Comment by hamzalodhi2023** [comment]
> Hey amigos! I'm Eftakhar Shaikh, a data magician turning numbers into compelling tales.
> 
> this line

Ok I will do this for you

**Comment by hamzalodhi2023** [comment]
Asalam'alaykum!

**Comment by hamzalodhi2023** [comment]
Overlapping problem has been solved.

**Comment by hamzalodhi2023** [comment]
Resume button added.

**Comment by Eftakharshaikh** [comment]
walekum as salama

**Comment by hamzalodhi2023** [comment]
Is website working correctly?

**Comment by hamzalodhi2023** [comment]
> Hey amigos! I'm Eftakhar Shaikh, a data magician turning numbers into compelling tales.
> 
> this line

Line has been added.

**Comment by Eftakharshaikh** [comment]
![Screenshot (55)](https://github.com/Eftakharshaikh/PortfolioWebsite/assets/147795895/0f117bf7-0470-4304-8f06-0e802adf439b)

some thing like this. font colour size depend on you

**Comment by hamzalodhi2023** [comment]
OK

**Comment by hamzalodhi2023** [comment]
Ok I will do this for you

**Comment by hamzalodhi2023** [comment]
Done, I have corrected this.

**Comment by Eftakharshaikh** [comment]
yes done, perfectly thankyou
